### ISSUE TITLE
Can one add mdg:reload-on-resume via hot code reloading?

### ISSUE THREAD

**Issue by hcvst** [meteor/mobile-packages#118] opened 2016-05-13 14:10 UTC
Hi,

I obviously need to learn how the hot code reloading mechanism really works. I had assumed the app would be patched on the user's device but now that I have added this package, all the apps that were installed prior to having added it refuse to update and are stuck on the version of the .apk / .ipa.

Are apps not patched, but rather download the latest version every time and now that I have added this package I have inadvertently broken that mechanism somehow?

Best regards,
Hans

**Comment by StorytellerCZ** [comment] 2021-09-30 17:47
I believe the problem is related to #72 , closing this in favor of #72.

**Closed by StorytellerCZ** 2021-09-30 17:47 UTC
Labels: question
