### ISSUE TITLE
geolocation does not work with Meteor 1.4+

### ISSUE THREAD

**Issue by MichelFloyd** [meteor/mobile-packages#127] opened 2017-01-24 22:56 UTC
Location is always returned as null.

**Comment by immigrantsheep** [comment] 2017-02-27 01:16
can confirm for me as well

**Comment by jrsakizci** [comment] 2017-05-15 13:07
Actually, it is working. But the problem is: when you enter site for the first time it returns null, but if you change route without reload the page, then its working. Strange error.

**Comment by jesperordrup** [comment] 2017-10-31 17:39
@jrsakizci 
Same here.. calling a few times then it works

**Comment by StorytellerCZ** [comment] 2021-09-29 12:47
Closing in favor of #133

**Closed by StorytellerCZ** 2021-09-29 12:47 UTC
