### ISSUE TITLE
Errors in console when using this package. Seems like it needs updating to use Meteor new Blaze API

### ISSUE THREAD

**Issue by sferoze** [meteor/mobile-packages#91] opened 2015-10-18 17:05 UTC
These are the errors I get in console when taking a picture with the meteor mobile camera package

```
Warning: Blaze.render without a parent element is deprecated. You must specify where to insert the rendered content.
blaze.js:38 Warning: Blaze.insert has been deprecated.  Specify where to insert the rendered content in the call to Blaze.render.
photo-browser.js:132 'MediaStream.stop()' is deprecated and will be removed in M47, around November 2015. Please use 'MediaStream.active' instead.
```

Or an image

<img width="1183" alt="screen shot 2015-10-18 at 1 04 34 pm" src="https://github-cloud.s3.amazonaws.com/assets/3514912/10565192/e423bf20-7598-11e5-9cb5-b525eef961da.png">

Also it seems like the UI elements are the old bootstrap. Can this be updated?

**Comment by minafarid** [comment] 2016-01-03 01:33
+1

**Comment by Kabangi** [comment] 2016-02-25 04:39
+1

**Comment by MaxArrowhead** [comment] 2016-03-09 14:19
+1
Or a React alternative

**Comment by ArjanKamphuis** [comment] 2016-03-23 01:53
To fix the deprecated warnings the last 2 lines in photo-browser.js:

```
- 209. view = UI.renderWithData(Template.camera);
- 210. UI.insert(view, document.body);
```

should be changed to single line:

```
- 209. view = Blaze.render(Template.camera, document.body);
```

**Comment by robertross** [comment] 2016-05-06 15:33
+1

**Comment by StorytellerCZ** [comment] 2021-08-25 13:00
Duplicate of #67, should be fixed now. Please comment if you are getting these errors in the latest version and we'll re-open the issue.

**Closed by StorytellerCZ** 2021-08-25 13:00 UTC
