### ISSUE TITLE
Camera not working on iOS 8?

### ISSUE THREAD

**Issue by lucascurti** [meteor/mobile-packages#45] opened 2015-02-04 01:48 UTC
I'm sure I must be missing something here since these are mobile packages but I can't seem to make the Camera work on IOS8 (Safari nor Chrome). I'm just getting a message that reads "Sorry, this browser is currently not supported for camera functionality".

Am I missing any package that should be added?

**Comment by stubailo** [comment] 2015-02-04 01:54
This package currently only works inside PhoneGap on iOS, not in the web browser.

**Comment by lucatros** [comment] 2015-02-04 01:55
Oh.. I see. Thanks for the quick reply!

**Comment by dandv** [comment] 2015-03-25 06:15
Same problem here. Is this a Safari limitation?

**Comment by lucatros** [comment] 2015-03-25 13:27
As mentioned on the comment above, this package doesn't work in the web
browser. Only inside PhoneGap

**Comment by dandv** [comment] 2015-03-25 17:07
@lucatros: it works great in the desktop version of Chrome and it works in Chrome on Android but the camera view snaps the first frame and stops, instead of continuously showing what the sensor sees.

**Comment by dandv** [comment] 2015-03-27 08:16
Updated my comment.

**Comment by lk1234** [comment] 2015-05-07 22:24
I'm still confused. I created an app, integrated it with Meteor/Cordova/Phonegap and deployed it on meteor.com, thinking then it would then work on ios mobile.  It still reads "Browser not supported." (I'm using it with Safari.). I'm very new at this, so may be missing something, even after reading the docs/comments...Is there any way to use the camera function with mobile ios and android? Thanks in advance.

**Comment by dandv** [comment] 2015-05-08 03:26
@lk1234: think of it this way: if you access your lk1234.meteor.com app from Safari, camera features won't work on *any* device, because as I wrote in my previous comment, the Safari *browser* doesn't support the API call to access the camera. This is regardless of adding the iOS platform to the Meteor app.

But, if you run the app on an iOS device with `meteor run ios`, camera *will* work - it will call the *camera app* on your iOS device. This is what Cordova does - provide the bridge from JavaScript calls to native APIs. On iOS, the app won't run in Safari, but in a [UIWebView](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIWebView_Class/) container, which, generally speaking, routes camera calls to the native app

Your confusion arises from associating Safari with the iOS app. See the two `photo-browser.js` and `photo-cordova.js` files in the [mdg:camera](https://github.com/meteor/mobile-packages/tree/master/packages/mdg:camera) package? They use different APIs, and Safari doesn't implement the `getUserMedia` API that photo-browser uses. Cordova and browser (whether Safari, Chrome or another) are different platforms.

**Comment by lk1234** [comment] 2015-05-08 10:18
That makes sense. Thanks for the explanation and quick reply, @dandv.

**Comment by luckyyang** [comment] 2015-06-03 01:53
Thanks for the explanation @dandv

**Comment by evolross** [comment] 2015-07-15 03:10
My app will be used across desktop, mobile web, and as a Cordova app.  I'm trying to add "Take Photo/Choose Photo" functionality on all three platforms.  

I just tested out Facebook in mobile Safari on my iPhone 6 and it accesses both the live camera and photo library flawlessly (prompting mobile Safari to request access to my camera too).  Is there some other Meteor package to do this on the mobile web?  

The only way I see currently is using the `mystor:device-detection` library to determine between desktop and phone and then using `Meteor.isCordova` to further determine between phone and Cordova.  Then using the results above to switch out the user-interface/templates.

Is this the current going strategy or is this solved already?

**Comment by rschreijer** [comment] 2015-08-22 11:57
@evolross did you ever find a way to get this working across all paltforms?

**Comment by evolross** [comment] 2015-08-24 16:18
Well I found out that on a mobile browser (at least in Safari on iOS) when you add an html file browser Safari automatically shows the buttons to "Take a Photo" or "Choose Photo".  So the same functionality I saw in Facebook in mobile Safari happens in my app too - for free!

I haven't tested Cordova yet, but I'm guessing that's why this package exists because it doesn't work like that when embedded inside Cordava.  Otherwise there would be no need for this package.  Can anyone confirm this?

**Comment by artsandideas** [comment] 2015-09-04 11:07
@evolross, could you outline exactly what you did to — "add an html file browser" ? We are experiencing the same issue. A code snippet would help. Thanks!

**Comment by evolross** [comment] 2015-09-04 21:30
`<input type="file">`

Google it to learn more about it.

**Comment by StorytellerCZ** [comment] 2021-09-29 13:14
Also see #7

**Comment by StorytellerCZ** [comment] 2021-09-30 14:56
Closing this as a duplicate of #7 , please continue the discussion there.

**Closed by StorytellerCZ** 2021-09-30 14:56 UTC
